---
AWSTemplateFormatVersion : 2010-09-09
Description: Creates the necessary pre-requisites resources for Sign to Speech and Speech to Sign language converter application.
Outputs:
  CognitoIdentityPoolID:
    Description: The Cognito Identity Pool ID. Place this in the AWS settings of your Amazon Sumerian Scene
    Value:
      Ref: CognitoIdentityPool
Resources:
    CognitoIdentityPool:
        Type: AWS::Cognito::IdentityPool
        Properties:
          IdentityPoolName:
            Fn::Sub: "ASLSumerianCognitoIdP${AWS::StackName}"
          AllowUnauthenticatedIdentities: True
    CognitoIdentityPoolUnAuthRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action: sts:AssumeRoleWithWebIdentity
              Effect: Allow
              Principal:
                Federated: 'cognito-identity.amazonaws.com'
              Condition:
                StringEquals:
                  cognito-identity.amazonaws.com:aud:
                    Ref: CognitoIdentityPool
          ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSIoTDataAccess
          - arn:aws:iam::aws:policy/AmazonPollyReadOnlyAccess
    CognitoRoleAttachment:
      Type: "AWS::Cognito::IdentityPoolRoleAttachment"
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          unauthenticated:
            Fn::GetAtt: [CognitoIdentityPoolUnAuthRole, Arn]







